<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Products;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
            'id' => 1,
            'product_categories_id' => 1,
            'name' => 'Asus ROG Zephyrus G14',
            'description' => 'Powerful gaming laptop with AMD Ryzen and RTX graphics.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 25000000,
            'stock' => 10,
            ],
            [
            'id' => 2,
            'product_categories_id' => 2,
            'name' => 'Acer Predator Helios 300',
            'description' => 'High-performance laptop for gaming and productivity.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 18000000,
            'stock' => 8,
            ],
            [
            'id' => 3,
            'product_categories_id' => 3,
            'name' => 'Dell XPS 13',
            'description' => 'Premium ultrabook with InfinityEdge display.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 22000000,
            'stock' => 12,
            ],
            [
            'id' => 4,
            'product_categories_id' => 4,
            'name' => 'HP Spectre x360',
            'description' => 'Convertible laptop with touch screen and stylus support.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 21000000,
            'stock' => 7,
            ],
            [
            'id' => 5,
            'product_categories_id' => 5,
            'name' => 'Lenovo Legion 5',
            'description' => 'Gaming laptop with AMD Ryzen and NVIDIA GeForce.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 17000000,
            'stock' => 9,
            ],
            [
            'id' => 6,
            'product_categories_id' => 6,
            'name' => 'MSI GF63 Thin',
            'description' => 'Affordable gaming laptop with slim design.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 14000000,
            'stock' => 11,
            ],
            [
            'id' => 7,
            'product_categories_id' => 7,
            'name' => 'Apple MacBook Air M2',
            'description' => 'Lightweight laptop with Apple Silicon M2 chip.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 19000000,
            'stock' => 6,
            ],
            [
            'id' => 8,
            'product_categories_id' => 8,
            'name' => 'Asus VivoBook S14',
            'description' => 'Stylish ultrabook with NanoEdge display.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 12000000,
            'stock' => 13,
            ],
            [
            'id' => 9,
            'product_categories_id' => 9,
            'name' => 'Acer Swift 3',
            'description' => 'Portable laptop with long battery life.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 11000000,
            'stock' => 14,
            ],
            [
            'id' => 10,
            'product_categories_id' => 10,
            'name' => 'HP Pavilion 14',
            'description' => 'Affordable laptop for everyday use.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 9000000,
            'stock' => 15,
            ],
            [
            'id' => 11,
            'product_categories_id' => 1,
            'name' => 'Dell Inspiron 15',
            'description' => 'Reliable laptop for work and study.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 8500000,
            'stock' => 10,
            ],
            [
            'id' => 12,
            'product_categories_id' => 2,
            'name' => 'Lenovo ThinkPad X1 Carbon',
            'description' => 'Business laptop with robust build quality.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 27000000,
            'stock' => 5,
            ],
            [
            'id' => 13,
            'product_categories_id' => 3,
            'name' => 'Asus ZenBook 13',
            'description' => 'Ultrabook with OLED display and long battery life.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 16000000,
            'stock' => 8,
            ],
            [
            'id' => 14,
            'product_categories_id' => 4,
            'name' => 'Acer Aspire 5',
            'description' => 'Budget laptop with solid performance.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 7000000,
            'stock' => 16,
            ],
            [
            'id' => 15,
            'product_categories_id' => 5,
            'name' => 'MSI Modern 14',
            'description' => 'Sleek laptop for productivity and entertainment.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 10000000,
            'stock' => 9,
            ],
            [
            'id' => 16,
            'product_categories_id' => 6,
            'name' => 'HP Envy 13',
            'description' => 'Premium laptop with slim design and fast SSD.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 15000000,
            'stock' => 7,
            ],
            [
            'id' => 17,
            'product_categories_id' => 7,
            'name' => 'Apple MacBook Pro 14',
            'description' => 'Professional laptop with Apple M1 Pro chip.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 32000000,
            'stock' => 4,
            ],
            [
            'id' => 18,
            'product_categories_id' => 8,
            'name' => 'Asus TUF Gaming F15',
            'description' => 'Durable gaming laptop with high refresh rate display.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 15500000,
            'stock' => 10,
            ],
            [
            'id' => 19,
            'product_categories_id' => 9,
            'name' => 'Lenovo IdeaPad Slim 3',
            'description' => 'Lightweight laptop for students and professionals.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 6500000,
            'stock' => 18,
            ],
            [
            'id' => 20,
            'product_categories_id' => 10,
            'name' => 'Acer Nitro 5',
            'description' => 'Popular gaming laptop with strong performance.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 13500000,
            'stock' => 11,
            ],
            [
            'id' => 21,
            'product_categories_id' => 1,
            'name' => 'HP EliteBook 840',
            'description' => 'Business-class laptop with security features.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 23000000,
            'stock' => 6,
            ],
            [
            'id' => 22,
            'product_categories_id' => 2,
            'name' => 'Dell G15',
            'description' => 'Gaming laptop with advanced cooling system.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 14500000,
            'stock' => 13,
            ],
            [
            'id' => 23,
            'product_categories_id' => 3,
            'name' => 'Asus ExpertBook B9',
            'description' => 'Ultra-light business laptop with long battery life.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 27000000,
            'stock' => 5,
            ],
            [
            'id' => 24,
            'product_categories_id' => 4,
            'name' => 'Lenovo Yoga Slim 7',
            'description' => 'Convertible laptop with flexible hinge.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 17500000,
            'stock' => 8,
            ],
            [
            'id' => 25,
            'product_categories_id' => 5,
            'name' => 'Acer Chromebook 14',
            'description' => 'Simple and fast Chromebook for web tasks.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 5000000,
            'stock' => 20,
            ],
            [
            'id' => 26,
            'product_categories_id' => 6,
            'name' => 'MSI Prestige 14',
            'description' => 'Elegant laptop for creators and professionals.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 18500000,
            'stock' => 7,
            ],
            [
            'id' => 27,
            'product_categories_id' => 7,
            'name' => 'HP Omen 16',
            'description' => 'Gaming laptop with high refresh rate display.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 21000000,
            'stock' => 6,
            ],
            [
            'id' => 28,
            'product_categories_id' => 8,
            'name' => 'Asus ROG Strix G15',
            'description' => 'RGB gaming laptop with powerful specs.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 24000000,
            'stock' => 8,
            ],
            [
            'id' => 29,
            'product_categories_id' => 9,
            'name' => 'Lenovo Flex 5',
            'description' => '2-in-1 convertible laptop for versatility.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 13000000,
            'stock' => 10,
            ],
            [
            'id' => 30,
            'product_categories_id' => 10,
            'name' => 'Acer Spin 5',
            'description' => 'Convertible laptop with stylus support.',
            'image' => 'https://cdn.thewirecutter.com/wp-content/media/2024/11/cheapgaminglaptops-2048px-7981.jpg',
            'price' => 15000000,
            'stock' => 9,
            ],
        ];

        foreach ($items as $item) {
            Products::create($item);
        }
    }
}
